import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sentra Tamansari",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

import Navbar from "../../components/navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
        {/* -----BOT UTAMA------- */}
        <script src="https://cdn.botpress.cloud/webchat/v3.0/inject.js" defer></script>
        <script src="https://files.bpcontent.cloud/2025/06/28/09/20250628090251-XSSRNXSQ.js" defer></script>
          
        {/* ------ BOT BACKUP ------- */}
        {/* <script src="https://cdn.botpress.cloud/webchat/v3.0/inject.js" defer></script>
        <script src="https://files.bpcontent.cloud/2025/05/15/01/20250515012432-3SDQKES6.js" defer></script> */}
    
      </body>
    </html>
  );
}